# Generated by Django 4.2.16 on 2025-02-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_videoasset_cdn_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoasset',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
