# Generated by Django 4.2.16 on 2025-06-10 02:02

from django.db import migrations
from django.utils.text import slugify

def populate_event_slugs(apps, schema_editor):
    Event = apps.get_model('events', 'Event')

    titles_seen = {}

    for event in Event.objects.all().order_by('id'):
        if not event.slug:
            base_slug = slugify(event.title)

            if base_slug in titles_seen:
                event.slug = f"{base_slug}-{event.id}"
            else:
                if Event.objects.filter(title=event.title).exclude(pk=event.pk).exists():
                    event.slug = f"{base_slug}-{event.id}"
                else:
                    event.slug = base_slug

                titles_seen[base_slug] = event.id

            event.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_slug'),
    ]

    operations = [
        migrations.RunPython(populate_event_slugs, reverse_code=migrations.RunPython.noop),
    ]
