# Generated by Django 4.2.21 on 2025-06-14 03:23

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_populate_event_slugs'),
    ]

    operations = [
        CreateExtension('pg_trgm'),
    ]
