name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
    - '**'


jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
        toxenv: [quality]

    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: pip install -r requirements/dev.txt

    - name: Run Tox
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
